name: pm2ls_client
description: \"I can't afford a mic\" - nori
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mic_stream: ^0.6.4
  opus_dart: ^3.0.0
  opus_flutter: ^3.0.1
  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
